<a href="https://colab.research.google.com/github/AkiraNom/data-analysis-notebook/blob/main/Colaboratory_%E3%81%B8%E3%82%88%E3%81%86%E3%81%93%E3%81%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sudoku Solver

This notebook implement to solve a sudoku.

Currently, you need to type a numpy array manually.

In future, try to implement a function to read an image and create a numpy array.

In [1]:
import numpy as np
import collections

In [261]:
def make_mask_grid(grid_size: int):
  """
  make a mask grid to find missing val in a grid

  Parameters:
  grid_size (int): determines the shape of the grid

  Return:
  grid (np.array): a mask grid
  """
  grid = np.ones((grid_size, grid_size), dtype=int)
  filter_size = int(np.sqrt(grid_size))
  base_mask = np.ones((filter_size, filter_size))

  grid_num = 1

  for i in range(0,grid_size,filter_size):
    for j in range(0,grid_size, filter_size):
      grid[i:i+filter_size,j:j+filter_size] = base_mask*grid_num
      grid_num +=1

  return grid

In [268]:
def search_missing_vals(array: np.array, max_val:int = 4, search_val:int =0):

  '''
  Search missing values in each row, column and grid of a sudoku puzzle

  Parameters:
  array (np.array): array to solve missing values
  max_vals(int): determines the value range to fill, default = 4 (expect 4*4)
  search_val(int): determines a search value in an array default = 0

  Return:
  missing_nums_list(dict): dictionary of missing values in each index
  '''
  grid_mask = make_mask_grid(max_val)
  missing_nums_list = {}

  # find index of val
  row_idx, col_idx = np.where(array == search_val) # (row1,row2....)(col1, col2....)
  for r, c in zip(row_idx, col_idx):

    row = array[r,:]
    col = array[:,c]
    grid_pos = (grid_mask == grid_mask[r,c])
    grid_val = array[grid_pos]

    # search missing num in row, col, and grid
    vals_list = list(range(1,max_val+1)) + [search_val]
    missing_num_row = [val for val in vals_list if val not in row]
    missing_num_col = [val for val in vals_list if val not in col]
    missing_num_grid = [val for val in vals_list if val not in grid_val]


    missing_nums_list[(r,c)] = missing_num_row + missing_num_col + missing_num_grid

  # import pdb; pdb.set_trace()

  return missing_nums_list


In [274]:
def solve_sudoku(array: np.array, max_val:int = 4, search_val:int =0)->bool:

  missing_nums_list = search_missing_vals(array, max_val, search_val)
  if not missing_nums_list:
    return True

  for index, vals in missing_nums_list.items():

    possible_vals = [val for val in set(vals) if vals.count(val) ==3]
    if len(possible_vals) == 1:
      array[index] = possible_vals[0]

      return solve_sudoku(array, max_val, search_val)

  return False


## 4X4 Test

In [275]:
arr = np.array([[0,0,0,4],[0,0,0,0],[2,0,0,3],[4,0,1,2]])
if solve_sudoku(arr):
  print('Solved sucessfully')
  print(arr)
else:
  print('Unable to solve the puzzle')

Solved sucessfully
[[1 2 3 4]
 [3 4 2 1]
 [2 1 4 3]
 [4 3 1 2]]


## 9 X 9 Test

In [276]:
arr_9x9 = np.array([
    [6,8,0,0,0,5,4,3,1],
    [0,0,7,9,0,4,2,6,5],
    [4,0,5,1,0,0,0,7,9],
    [2,5,8,4,0,0,0,9,3],
    [0,0,0,0,9,0,1,0,4],
    [0,0,0,8,6,3,0,0,7],
    [7,1,3,0,0,0,9,4,0],
    [0,9,0,6,0,0,0,0,8],
    [8,0,0,0,0,0,7,0,2]
    ])
if solve_sudoku(arr_9x9, max_val=9):
  print('Solved sucessfully')
  print(arr_9x9)
else:
  print('Unable to solve the puzzle')

Solved sucessfully
[[6 8 9 7 2 5 4 3 1]
 [1 3 7 9 8 4 2 6 5]
 [4 2 5 1 3 6 8 7 9]
 [2 5 8 4 7 1 6 9 3]
 [3 7 6 5 9 2 1 8 4]
 [9 4 1 8 6 3 5 2 7]
 [7 1 3 2 5 8 9 4 6]
 [5 9 2 6 4 7 3 1 8]
 [8 6 4 3 1 9 7 5 2]]
